# Generated by Django 5.1.1 on 2024-09-18 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_crisis_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='added_by',
        ),
        migrations.AddField(
            model_name='crisis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
