# Generated by Django 5.1.1 on 2024-09-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_age_user_assigned_tasks_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_tasks',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='core.task'),
        ),
    ]
