# Generated by Django 5.1.1 on 2024-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
