# Generated by Django 5.1.1 on 2024-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventoryitem_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='created_by',
            field=models.CharField(default='Anonymous user', max_length=200),
        ),
    ]
